services:
  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: php_container
    volumes:
      - ./backend:/var/www
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: datafrete
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    ports:
      - "3306:3306"
    networks:
      - app-network

  vuejs:
    image: node:14
    container_name: vuejs_container
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run serve"
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "8081:8080"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www
      - ./backend/.docker/nginx:/etc/nginx/conf.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: